# Generated by Django 5.2.1 on 2025-06-25 15:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import presentations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_event_created_at_alter_event_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='발표 제목')),
                ('description', models.TextField(verbose_name='발표 내용 설명')),
                ('content_md', models.TextField(blank=True, help_text='발표 상세 내용을 마크다운으로 작성하세요', verbose_name='마크다운 내용')),
                ('file_url', models.FileField(blank=True, help_text='PDF, PPT, PPTX 파일 업로드 (최대 50MB)', null=True, upload_to=presentations.models.presentation_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx']), presentations.models.validate_file_size], verbose_name='발표 자료')),
                ('status', models.CharField(choices=[('submitted', '신청됨'), ('selected', '선정됨'), ('completed', '완료됨'), ('rejected', '거절됨')], default='submitted', max_length=20, verbose_name='상태')),
                ('selected_for_newsletter', models.BooleanField(default=False, help_text='이 발표를 뉴스레터에 포함할지 여부', verbose_name='뉴스레터 포함 여부')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='events.event', verbose_name='이벤트')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to=settings.AUTH_USER_MODEL, verbose_name='발표자')),
            ],
            options={
                'verbose_name': '발표',
                'verbose_name_plural': '발표',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('guest_name', models.CharField(blank=True, help_text='비회원 댓글 작성자명', max_length=100)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='presentations.presentation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentation_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
