# Generated by Django 5.2.1 on 2025-06-25 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='장소명')),
                ('address', models.TextField(verbose_name='주소')),
                ('description', models.TextField(blank=True, verbose_name='장소 설명')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='최대 수용인원')),
            ],
            options={
                'verbose_name': '장소',
                'verbose_name_plural': '장소들',
                'constraints': [models.CheckConstraint(condition=models.Q(('max_capacity__gt', 0)), name='max_capacity_positive')],
            },
        ),
    ]
